# prod/infra-services/harbor-chart.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: infra-services
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.goharbor.io
      chart: harbor
      version: 1.10.2
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  values:
    harborAdminPassword: changeme
    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          claimName: harbor-registry
        chartmuseum:
          claimName: harbor-chartmuseum
        jobservice:
          claimName: harbor-jobservice
        database:
          claimName: harbor-database
        redis:
          claimName: harbor-redis
    externalURL: https://harbor.diggity00.net
